# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dna_model_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dna_model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dna_model_pb2 as dna__model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64na_model_service.proto\x1a\x0f\x64na_model.proto2\xff\x03\n\x0f\x44naModelService\x12J\n\x0fPredictSequence\x12\x17.PredictSequenceRequest\x1a\x18.PredictSequenceResponse\"\x00(\x01\x30\x01\x12J\n\x0fPredictInterval\x12\x17.PredictIntervalRequest\x1a\x18.PredictIntervalResponse\"\x00(\x01\x30\x01\x12G\n\x0ePredictVariant\x12\x16.PredictVariantRequest\x1a\x17.PredictVariantResponse\"\x00(\x01\x30\x01\x12\x44\n\rScoreInterval\x12\x15.ScoreIntervalRequest\x1a\x16.ScoreIntervalResponse\"\x00(\x01\x30\x01\x12\x41\n\x0cScoreVariant\x12\x14.ScoreVariantRequest\x1a\x15.ScoreVariantResponse\"\x00(\x01\x30\x01\x12J\n\x0fScoreIsmVariant\x12\x17.ScoreIsmVariantRequest\x1a\x18.ScoreIsmVariantResponse\"\x00(\x01\x30\x01\x12\x36\n\x0bGetMetadata\x12\x10.MetadataRequest\x1a\x11.MetadataResponse\"\x00\x30\x01\x42\x9b\x01\n,com.google.gdm.gdmscience.alphagenome.v1mainB\x14\x44naModelServiceProtoP\x01ZSgoogle.golang.org/genproto/googleapis/gdm/gdmscience/alphagenome/v1main;alphagenomeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dna_model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.google.gdm.gdmscience.alphagenome.v1mainB\024DnaModelServiceProtoP\001ZSgoogle.golang.org/genproto/googleapis/gdm/gdmscience/alphagenome/v1main;alphagenome'
  _globals['_DNAMODELSERVICE']._serialized_start=45
  _globals['_DNAMODELSERVICE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
