version: '3.8'

services:
  alphagenome-proxy:
    build: .
    ports:
      - "50051:50051"  # gRPC port
      - "8000:8000"    # JSON service port
    environment:
      - JSON_SERVICE_BASE_URL=http://localhost:8000
      - ALPHAGENOME_API_KEY=${ALPHAGENOME_API_KEY}
      - API_KEY_HEADER=Authorization
      - API_KEY_PREFIX=Bearer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/docs', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - alphagenome-network

networks:
  alphagenome-network:
    driver: bridge
